{
  "param_dir": "../../build/data", #生成した遺伝子が保存されているパス
  "param_size": 13125, #評価関数のパラメータサイズ(dekunobou.hppのparam_sizeと値を揃える)
  "gene_num": 1024, #GAを行う際の遺伝子数(ga.hppのNと値を揃える)
  "move_h": 480,
  "move_w": 640,
  "aspect": 10, #ヒートマップのアスペクト比
  "img_dir": "out", #画像の保存先
  "mov_dir": "mov", #動画の保存先
}
