{
    "engine1": "../../build/dekunobou", #対戦させたいエンジンのパス
    "engine2": "../../build/dekunobou", #対戦させたいエンジンのパス
    "match_times": 100, #対戦させる回数
    "record_path": "match_record.txt", #対戦した棋譜の保存先. 1行に1対戦分の棋譜が保存される.
}